### create a report
POST http://localhost:3000/reports
content-type :application/json

{
    "make" : "user2 car",
    "model" : "breeza",
    "year" : 2000,
    "mileage" : 10000,
    "lng" : 0,
    "lat" : 0,
    "price" : 10000
}

### approve an existing report
PATCH http://localhost:3000/reports/6
content-type :application/json

{
    "approved" : true
}

### get an estimate for an existing vehicle
GET http://localhost:3000/reports?make=tesla&lng=0&lat=0&mileage=10000&year=2000&model=breeza