### create user / sign up
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email" : "8@gmail.com",
    "password" : "pass"
} 

### sign in / login
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email" : "4@gmail.com",
    "password" : "pass"
} 

### get the current session user ( who am i ) 
GET http://localhost:3000/auth/whoami

### signout
POST http://localhost:3000/auth/signout

### find a user with a given id
GET http://localhost:3000/auth/1

### find all users with a given email
GET http://localhost:3000/auth?email=1@gmail.com

### delete an user by an id
DELETE http://localhost:3000/auth/1

### update user by providing an id
PATCH http://localhost:3000/auth/20
content-type: 'application/json'

{
    "email" : "updated@gmail.com"
}

### set a color
GET http://localhost:3000/auth/colors/red

### get the color
GET http://localhost:3000/auth/colors